package com.course.atcrowdfunding.potal.dao;

import com.course.atcrowdfunding.bean.Form;
import java.util.List;

public interface FormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    int insert(Form record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    Form selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    List<Form> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    int updateByPrimaryKey(Form record);

	List<Form> selectByMemberid(Integer id);
}