package com.course.atcrowdfunding.potal.dao;


import java.util.List;

import com.course.atcrowdfunding.bean.Project;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Sat Oct 05 21:17:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Sat Oct 05 21:17:34 CST 2019
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Sat Oct 05 21:17:34 CST 2019
     */
    Project selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Sat Oct 05 21:17:34 CST 2019
     */
    List<Project> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbggenerated Sat Oct 05 21:17:34 CST 2019
     */
    int updateByPrimaryKey(Project record);

	List<Project> selectByMemberid(Integer id);

	List<Project> selectStatus(String string);
}