package com.course.atcrowdfunding.potal.dao;

import com.course.atcrowdfunding.bean.Return;
import java.util.List;

public interface ReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    int insert(Return record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    Return selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    List<Return> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    int updateByPrimaryKey(Return record);

	List<Return> selectByProjectid(Integer projectid);
}