package com.course.atcrowdfunding.bean;

import java.util.Date;

public class Form {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.id
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.returnid
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    private Integer returnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.memberid
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.status
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.money
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.date
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.id
     *
     * @return the value of t_form.id
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.id
     *
     * @param id the value for t_form.id
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.returnid
     *
     * @return the value of t_form.returnid
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    public Integer getReturnid() {
        return returnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.returnid
     *
     * @param returnid the value for t_form.returnid
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    public void setReturnid(Integer returnid) {
        this.returnid = returnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.memberid
     *
     * @return the value of t_form.memberid
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.memberid
     *
     * @param memberid the value for t_form.memberid
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.status
     *
     * @return the value of t_form.status
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.status
     *
     * @param status the value for t_form.status
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.money
     *
     * @return the value of t_form.money
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.money
     *
     * @param money the value for t_form.money
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.date
     *
     * @return the value of t_form.date
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.date
     *
     * @param date the value for t_form.date
     *
     * @mbggenerated Tue Oct 08 16:16:46 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }
}