package com.course.atcrowdfunding.bean;

public class Return {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.id
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.projectid
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.type
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.supportmoney
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    private Integer supportmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.content
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.count
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.freight
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    private Integer freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.invoice
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    private String invoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.rtndate
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    private Integer rtndate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.id
     *
     * @return the value of t_return.id
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.id
     *
     * @param id the value for t_return.id
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.projectid
     *
     * @return the value of t_return.projectid
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.projectid
     *
     * @param projectid the value for t_return.projectid
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.type
     *
     * @return the value of t_return.type
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.type
     *
     * @param type the value for t_return.type
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.supportmoney
     *
     * @return the value of t_return.supportmoney
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public Integer getSupportmoney() {
        return supportmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.supportmoney
     *
     * @param supportmoney the value for t_return.supportmoney
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public void setSupportmoney(Integer supportmoney) {
        this.supportmoney = supportmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.content
     *
     * @return the value of t_return.content
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.content
     *
     * @param content the value for t_return.content
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.count
     *
     * @return the value of t_return.count
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.count
     *
     * @param count the value for t_return.count
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.freight
     *
     * @return the value of t_return.freight
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public Integer getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.freight
     *
     * @param freight the value for t_return.freight
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public void setFreight(Integer freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.invoice
     *
     * @return the value of t_return.invoice
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public String getInvoice() {
        return invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.invoice
     *
     * @param invoice the value for t_return.invoice
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public void setInvoice(String invoice) {
        this.invoice = invoice == null ? null : invoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.rtndate
     *
     * @return the value of t_return.rtndate
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public Integer getRtndate() {
        return rtndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.rtndate
     *
     * @param rtndate the value for t_return.rtndate
     *
     * @mbggenerated Sun Oct 06 20:55:09 CST 2019
     */
    public void setRtndate(Integer rtndate) {
        this.rtndate = rtndate;
    }
}